/**
 * @fileoverview A React component that provides a guided AI study helper.
 * It takes a user's topic, calls a Genkit flow to get a structured
 * response, and displays it.
 */
'use client';

import { getTopicHelp, GetTopicHelpOutput } from '@/ai/flows/ai-powered-category-help';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useState } from 'react';
import { Loader, Wand2, RefreshCw, Bot } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

export default function AICategoryHelp() {
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<GetTopicHelpOutput | null>(null);

  const handleGenerate = async () => {
    if (!topic) {
      setError('Please enter a topic.');
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await getTopicHelp({ topic });
      setResult(response);
    } catch (e: any) {
      setError(e.message || 'An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setTopic('');
    setResult(null);
    setError(null);
    setLoading(false);
  };

  return (
    <div className="space-y-4">
      {!result && !loading && (
        <div className="flex w-full items-center space-x-2">
          <Input
            type="text"
            placeholder="e.g., Data Structures, Quantum Physics..."
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && !loading && handleGenerate()}
            disabled={loading}
            className="text-base"
          />
          <Button onClick={handleGenerate} disabled={loading} className="px-6">
            <Wand2 className="mr-2 h-4 w-4" />
            Explain
          </Button>
        </div>
      )}

      {loading && (
        <div className="flex items-center justify-center rounded-lg border border-dashed p-8">
          <Loader className="mr-3 h-6 w-6 animate-spin text-primary" />
          <p className="text-muted-foreground">Generating insights...</p>
        </div>
      )}

      {error && <p className="text-sm text-destructive">{error}</p>}

      {result && (
        <Card className="animate-fade-in-up bg-secondary/50">
           <CardHeader>
            <div className="flex justify-between items-start">
              <div className="space-y-1.5">
                <CardTitle className='flex items-center gap-2'><Bot className="h-6 w-6 text-primary" />AI Response for: {topic}</CardTitle>
                <CardDescription>Generated by EduBot AI</CardDescription>
              </div>
               <Button onClick={handleReset} variant="ghost" size="icon">
                  <RefreshCw className="h-4 w-4" />
                  <span className="sr-only">Start Over</span>
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <h3 className="font-semibold text-base mb-2 text-foreground">Description</h3>
              <p className="text-sm text-muted-foreground">{result.description}</p>
            </div>
            <div>
              <h3 className="font-semibold text-base mb-2 text-foreground">Related Topics</h3>
              <ul className="list-disc list-inside space-y-1">
                {result.relatedTopics.map((relatedTopic, index) => (
                  <li key={index} className="text-sm text-muted-foreground">{relatedTopic}</li>
                ))}
              </ul>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
